---
title: "Data Wrangling_Tutorial"
author: "Bimal"
date: "December 5, 2015"
output: html_document
---
        
Data Wranlging :
        
Reshape:
        
Pew Dataset
        
```{r}
pew <- read.delim(
        file = "http://stat405.had.co.nz/data/pew.txt",
        header = TRUE,
        stringsAsFactors = FALSE,
        check.names = FALSE)
head(pew)
tail(pew)
summary(pew)
```
        
Making pew data tidy using melt fucntion in Reshape2 
```{r}
library(reshape2)
pew_tidy <- melt(
        data = pew,
        id.vars = "religion",
        variable.name = "income",
        value.name = "frequency")
                
head(pew_tidy)
tail(pew_tidy)
summary(pew_tidy)

```
Assignment : Split gender and Age from tuborclosis dataset.

Reading TB dataset!
```{r}
tb <- read.csv(
        file = "http://stat405.had.co.nz/data/tb.csv",
        header = TRUE,
        stringsAsFactors = FALSE)
head(tb)
tail(tb)
summary(tb)
```

Making the Data Tidy!
```{r}
library(reshape2)
# Set column newsp as NULL and clean up the rest of the colums
# gsub is used to identify the pattern and replace it with a new one!
tb$new_sp = NULL
names(tb) <- gsub(
                pattern = "new_sp_",
                x = names(tb),
                ignore.case = FALSE,
                replacement = "")
head(tb)

# Cleaning up the data ! 
tb_tidy <- melt(data = tb,
                na.rm = TRUE,
                id = c("iso2","year"),
                variable.name = "gender_age",
                value.name = "cases"
                )
head(tb_tidy)
tail(tb_tidy)
summary(tb_tidy)

# splitting Age and Gender!
library(plyr)
tb_tidy <- mutate(tb_tidy,
        gender = sub("^([m|f])(.*)$", "\\1", gender_age),
        age = sub("^([m|f])(.*)$", "\\2", gender_age),
        gender_age = NULL
        )
tb_tidy <- tb_tidy[c('iso2', 'year', 'gender', 'age', 'cases')]

head(tb_tidy)
tail(tb_tidy)
summary(tb_tidy)
```

Assignment : Cleaning weather dataset 

```{r}

weather <-read.delim(
        file = "https://ramnathv.github.io/pycon2014-r/explore/data/weather.txt",
        stringsAsFactors = FALSE)

head(weather)
tail(weather)


# cleaning up the days variable name#
library(reshape2)
weather_tidy <- melt(
        data = weather,
        na.rm = TRUE,
        id = c("id","year","month","element"),
        value.name = "temperature",
        variable.name = "day"
        )
# cleaning up the day values using mutate function!
weather_tidy <- mutate(
        weather_tidy,
        day = sub("^[d]","",day)
        )
# using dcast function to convert the element row values into variable names! 
weather_tidy <- dcast(data = weather_tidy,
                      formula = id + year + month + day ~ element,
                      value.var = "temperature")

head(weather_tidy)
tail(weather_tidy)

```
Billiboard data set :

```{r}
library(reshape2)
billiboards <- read.csv(
        file = "http://stat405.had.co.nz/data/billboard.csv",
        stringsAsFactors = FALSE
        )

names(billiboards) <- gsub("\\.","_",names(billiboards))

billiboards <- mutate(
        billiboards,
        artist_inverted = iconv(artist_inverted,"MAC","UTF-8")
        )

billiboards_tidy <- melt(
                billiboards,
                id = 1:7,
                variable.name = "week",
                value.name = "rank",
                na.rm = TRUE
)


head(billiboards)
tail(billiboards)
```
